version: '2'

services:
  elasticsearch:
    build: elasticsearch/
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    networks:
      - elk

  logstash:
    build: logstash/
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_HOST: "elasticsearch"
      ELASTIC_USER: "elastic"
      ELASTIC_PASS: "changeme"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elk
    environment:
      ELASTIC_HOST: "http://elasticsearch:9200"
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
